name: test yaml

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  bash-example:
    runs-on: ubuntu-latest
    outputs:
      is_avlo_requirements: $${{ steps.test.outputs.is_avlo_requirements }}
      is_avlo_testcases: $${{ steps.test.outputs.is_avlo_testcases }}
      system_path: $${{ steps.test.outputs.system_path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Group of log lines
        id: test
        run: |
            echo "::endgroup:: $(pwd)"
            chmod +x ./test.sh
            ./test.sh

  bash-example-2:
    runs-on: ubuntu-latest
    needs: bash-example
    if: ${{ needs.bash-example.outputs.is_avlo_requirements == true }}
    steps:
      - env:
          OUTPUT1: ${{needs.bash-example.outputs.is_avlo_requirements}}
          OUTPUT2: ${{needs.bash-example.outputs.is_avlo_testcases}}
          OUTPUT3: ${{needs.bash-example.outputs.system_path}}

        run: |
            echo "group::Mytitle"
            echo "Debug: is_avlo_requirements=${{ needs.bash-example.outputs.is_avlo_requirements }}"
            echo "$OUTPUT1 $OUTPUT2 $OUTPUT3"

