name: test yaml

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  bash-example:
    runs-on: ubuntu-latest
    outputs:
      is_flag: $${{ steps.test.outputs.is_flag }}
    steps:
      - name: Group of log lines
        id: test
        run: |
            echo "::endgroup:: $(pwd)"
            ls
            pwd
            #echo "is_flag=true" >> "$GITHUB_OUTPUT"
            #chmod +x ./test.sh
            #./test.sh

  bash-example-2:
    runs-on: ubuntu-latest
    needs: bash-example
    steps:
      - env:
          OUTPUT1: ${{needs.bash-example.outputs.is_flag}}
        run: |
            echo "::group::My title"
            echo "$OUTPUT1"

