name: test yaml

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  bash-example:
    runs-on: ubuntu-latest

    outputs:
      is_flag: $$ {{ steps.test.outputs.is_flag }}
    steps:
      - name: Group of log lines
        id: test
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
            echo "is_flag=hello" >> $GITHUB_OUTPUT
            echo "is_flag=${{ steps.test.outputs.is_flag }}"

